apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo-app-ingress-external
  annotations:
    # Attach Traefik BasicAuth middleware (namespace-middleware@kubernetescrd)
    traefik.ingress.kubernetes.io/router.middlewares: monitoring-stage-echo-basicauth@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: demoapp.sixthnode.external.stage.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: echo-server
                port:
                  number: 80
