apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring-stage

labels:
  - includeSelectors: true
    pairs:
      env: stage

resources:
  - ingress-echo-app.yaml
  # Debug: no-auth ingress (remove when done)
  - ingress-echo-app-debug-noauth.yaml
