apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: echo-basicauth
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  basicAuth:
    secret: bw-basic-auth
    realm: "Authentication Required"
