apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-settings-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: observability
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  source:
    repoURL: 'https://github.com/sixthnode/poc-aks-helm-argocd.git'
    path: kustomizations/observability/overlays/prod
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSync=true
      - Replace=true
      - Prune=true

